/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_LlamaJNI */

#ifndef _Included_com_example_LlamaJNI
#define _Included_com_example_LlamaJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_LlamaJNI
 * Method:    generateResponse
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_LlamaJNI_generateResponse
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
